//Users
export const GET_USERS = 'GET_USERS';
export const PUT_USER = 'PUT_USER';
export const DELETE_USER = 'DELETE_USER';
export const CREATE_USER = 'CREATE_USER';
export const GET_ONE_USER = 'GET_ONE_USER';
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const GET_USERS_ORDERS = 'GET_USERS_ORDERS';
export const USER_PUT_PASSWORD = 'USER_PUT_PASSWORD';
//Users loguin
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CURRENT_USER = 'CURRENT_USER';
export const NOT_CURRENT_USER = 'NOT_CURRENT_USER';
export const DELETE_ALL_CART = 'DELETE_ALL_CART';

// Up User
export const UP_USER = 'UP_USER';
export const UPDATE_USER = 'UPDATE_USER';

//Acount
export const GET_ACCOUNT = 'GET_ACCOUNT'
export const RECHARGE_QR = 'RECHARGE_QR'
export const RECHARGE_CARD = 'RECHARGE_CARD'
export const TRANSFER_MONEY = 'TRANSFER_MONEY'
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const GET_TRANSACTIONS_DOLAR = 'GET_TRANSACTIONS_DOLAR'
export const GET_TRANSACTIONS_PESOS = 'GET_TRANSACTIONS_PESOS'
export const GET_TRANSACTIONS_DOLLARS = 'GET_TRANSACTIONS_DOLLARS';
export const GET_TRANSACTIONS_PESOS_GRAP = 'GET_TRANSACTIONS_PESOS_GRAP'

//Contact 
export const GET_CONTACTS = 'GET_CONTACTS'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const ADD_CONTACT_EMAIL = 'ADD_CONTACT_EMAIL'
export const ADD_CONTACT_PHONE = 'ADD_CONTACT_PHONE'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const SEND_WHATSAPP = 'SEND_WHATSAPP'
export const BALANCE_PESOS_EGRESOS = 'BALANCE_PESOS_EGRESOS'
export const BALANCE_PESOS_INGRESOS = 'BALANCE_PESOS_INGRESOS'



//Contact
// export const GET_CONTACTS = 'GET_CONTACTS';
// export const EDIT_CONTACT = 'EDIT_CONTACT';
// export const ADD_CONTACT_EMAIL = 'ADD_CONTACT_EMAIL';
// export const ADD_CONTACT_PHONE = 'ADD_CONTACT_PHONE';
// export const DELETE_CONTACT = 'DELETE_CONTACT';
// export const SEND_WHATSAPP = 'SEND_WHATSAPP';
